package io.vertx.starter.storage.cassandra.udt;

import com.datastax.driver.mapping.annotations.Field;
import com.datastax.driver.mapping.annotations.UDT;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;

/**
 * GENERATED CODE DO NOT MODIFY - last updated: 2017-02-20T06:11:58.831Z
 * generated by exovert - https://github.com/cyngn/exovert
 *
 * UDT class for Cassandra - formatter
 */
@UDT(
    keyspace = "ks",
    name = "formatter"
)
public class Formatter {
  @Field
  @JsonProperty
  public String element;

  @Field
  @JsonProperty
  public String name;

  @Field
  @JsonProperty
  public String type;

  @Field
  @JsonProperty
  public String id;

  @Field
  @JsonProperty
  public String gateway;

  public void setElement(String element) {
    this.element = element;
  }

  public String getElement() {
    return element;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getType() {
    return type;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getId() {
    return id;
  }

  public void setGateway(String gateway) {
    this.gateway = gateway;
  }

  public String getGateway() {
    return gateway;
  }

  @Override
  public String toString() {
    return "Formatter{" +
    "element=" + element +
    ", name=" + name +
    ", type=" + type +
    ", id=" + id +
    ", gateway=" + gateway +
    "}";
  }
}
