package io.vertx.starter.storage.cassandra.dal;

import com.datastax.driver.mapping.Result;
import com.datastax.driver.mapping.annotations.Accessor;
import com.datastax.driver.mapping.annotations.Query;
import com.google.common.util.concurrent.ListenableFuture;
import io.vertx.starter.storage.cassandra.table.Messages;

/**
 * GENERATED CODE DO NOT MODIFY - last updated: 2017-02-20T06:11:58.831Z
 * generated by exovert - https://github.com/cyngn/exovert
 *
 * Accessor for Cassandra entity - {@link io.vertx.starter.storage.cassandra.table.Messages}
 */
@Accessor
public interface MessagesAccessor {
  @Query("SELECT * FROM ks.messages")
  ListenableFuture<Result<Messages>> getAll();
}
