package io.vertx.starter.storage.cassandra.table;

import com.datastax.driver.mapping.annotations.Column;
import com.datastax.driver.mapping.annotations.FrozenValue;
import com.datastax.driver.mapping.annotations.PartitionKey;
import com.datastax.driver.mapping.annotations.Table;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.starter.storage.cassandra.udt.Formatter;
import java.lang.Override;
import java.lang.String;
import java.util.Date;
import java.util.List;

/**
 * GENERATED CODE DO NOT MODIFY - last updated: 2017-02-20T06:11:58.831Z
 * generated by exovert - https://github.com/cyngn/exovert
 *
 * Table class for Cassandra - messages
 */
@Table(
    keyspace = "ks",
    name = "messages"
)
public class Messages {
  @Column
  @JsonProperty
  @PartitionKey(0)
  public String id;

  @Column
  @JsonProperty
  public String category;

  @Column
  @JsonProperty
  public Date date;

  @Column
  @JsonProperty
  public String message;

  @Column(name = "message_from")
  @JsonProperty("message_from")
  public String messageFrom;

  @Column(name = "message_to")
  @JsonProperty("message_to")
  public String messageTo;

  @FrozenValue
  @Column
  @JsonProperty
  public List<Formatter> meta;

  @Column
  @JsonProperty
  public String origin;

  @Column
  @JsonProperty
  public String status;

  public void setId(String id) {
    this.id = id;
  }

  public String getId() {
    return id;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public String getCategory() {
    return category;
  }

  public void setDate(Date date) {
    this.date = date;
  }

  public Date getDate() {
    return date;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getMessage() {
    return message;
  }

  public void setMessageFrom(String messageFrom) {
    this.messageFrom = messageFrom;
  }

  public String getMessageFrom() {
    return messageFrom;
  }

  public void setMessageTo(String messageTo) {
    this.messageTo = messageTo;
  }

  public String getMessageTo() {
    return messageTo;
  }

  public void setMeta(List<Formatter> meta) {
    this.meta = meta;
  }

  public List<Formatter> getMeta() {
    return meta;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public String getOrigin() {
    return origin;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getStatus() {
    return status;
  }

  @Override
  public String toString() {
    return "Messages{" +
    "id=" + id +
    ", category=" + category +
    ", date=" + date +
    ", message=" + message +
    ", messageFrom=" + messageFrom +
    ", messageTo=" + messageTo +
    ", meta=" + meta +
    ", origin=" + origin +
    ", status=" + status +
    "}";
  }
}
